---
- name: restart postgresql-9.6
  service: name=postgresql-9.6 state=restarted

- name: restart firewalld
  service: name=firewalld state=restarted

- name:  systemctl daemon-reload
  service: name=systemctl state=daemon-reload
