---
- name: Install Packages from  Repo
  include: install.yml
  when: enable_wildfly

- name: create directory | etc/wildfly
  file: path=/etc/wildfly  state=directory 
  tags:
    - wildfly

- name: create wildfly Config
  template: src=wildfly.conf.j2 dest=/etc/wildfly/wildfly.conf  owner=wildfly group=wildfly
  tags:
    - wildfly

- name: create wildfly service
  template: src=wildfly.service.j2 dest=/etc/systemd/system/wildfly.service 
  tags: 
    - wildfly

- name: create wildfly bin
  template: src=launch.sh.j2 dest={{ wildfly_dir }}/bin/launch.sh  mode=755 owner=wildfly group=wildfly
  tags: 
    - wildfly 

- name:  Start and Enable wildfly
  service: name=wildfly  state=started  enabled=yes

- name: Create management users
  shell: >
       {{ wildfly_dir }}/bin/add-user.sh -u {{ user }} {{ password }} -s -e && touch {{ wildfly_dir }}/standalone/configuration/.mgmt-users.{{ user }}.provisioned
  #with_items: "{{ wildfly_management_users }}"
  #become: True
  #become_user: '{{ wildfly_user }}'
  args:
    creates: "{{ wildfly_dir }}/standalone/configuration/.mgmt-users.unicred.provisioned"
  when: wildfly_management_users | length > 0
  #no_log: True
  tags:
    - wildfly

- name: Enforce secure permissions on password files
  file:
    path: "{{ wildfly_dir }}/standalone/configuration/{{ item }}"
    owner: "{{ wildfly_user }}"
    group: "{{ wildfly_group }}"
    mode: "0600"
  with_items:
    - mgmt-groups.properties
    - mgmt-users.properties
  tags:
    - wildfly

- name: Enforce secure permissions on password files
  file:
    path: "{{ wildfly_dir }}/domain/configuration/{{ item }}"
    owner: "{{ wildfly_user }}"
    group: "{{ wildfly_group }}"
    mode: "0600"
  with_items:
    - mgmt-groups.properties
    - mgmt-users.properties

  tags:
    - wildfly

- name: Install Drivers JBDC
  include: drivers.yml
  when: enable_wildfly_drivers
  tags:
    - wildfly  
